### ISSUE TITLE
How use py6S in google colaboratory? problem "cannot find the sixs executable in $PATH or current directory"

### ISSUE THREAD

**Issue by felipefariadesousa** [robintw/Py6S#105]
Hi Robin! 

I am very excited to use py6S on google collaborative, but I am getting the following error "Error: cannot find the sixs executable in $PATH or current directory." 

I installed using the pip install command

**Comment by fnemina** [comment]
Hello,

I had the same problem and had to manually copy the `sixs` executable and add it to the path. Here is how to do this

```python
!pip install py6s
!apt install gfortran libgfortran5
!wget https://anaconda.org/conda-forge/sixs/1.1.3/download/linux-64/sixs-1.1.3-h2cc385e_2.tar.bz2
!tar -xvf sixs-1.1.3-h2cc385e_2.tar.bz2
!rm sixs-1.1.3-h2cc385e_2.tar.bz2
!chmod +x bin/sixs
!ln bin/sixs /usr/local/bin/sixs
```

just copy this code into a cell and run it, it will install py6s with pip, download the necessary libraries, get the `sixs` executable and copy it to the correct folder.

You can check and example [here](https://colab.research.google.com/drive/10QMfdkQCQJmfOsIVQKI46UL_qJUrFJIW?usp=sharing).

Hope this works for you,
Fran

**Comment by felipefariadesousa** [comment]
Hello,

Thank you very much for taking your time to help me. I'm happy to say it's working perfectly now! 

Thanks!
