### ISSUE TITLE
need to add -ffpe-summary=none to gfortran flags to prevent warning in 6S output

### ISSUE THREAD

**Issue by vincentschut** [robintw/Py6S#15]
If 6S is compiled (linux, debian testing, gfortran4.9) with the flags as in the Py6S documentation, sixs.test() fails because at the end of the 6S output a warning is printed: "Note: The following floating-point exceptions are signalling: IEEE_INVALID_FLAG". This can be suppressed by adding "-ffpe-summary=none" to the gfortran flags in the Makefile. When compiled with this flag, sixs.test() runs fine.

-> might be a good idea to update the documentation in the linux install section.

**Comment by robintw** [comment]
Thanks - this is very helpful. I've added it to the docs.

**Comment by pbowyer** [comment]
Just a note that this flag isn't present in `gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04)`. I omitted it and the the program built without issue.

**Comment by ernetas** [comment]
:+1: for what @pbowyer said. The current docs version actually confused me on Ubuntu 14.04.
