### ISSUE TITLE
Add importer for spectra from NERC FSF instruments

### ISSUE THREAD

**Issue by danclewley** [robintw/Py6S#25]
Add importers for spectra collected using field spectrometers to `Py6S.SixSHelpers.spectra`. Specifically make importer for .sig format files, developed by @arsf for internal use, available within Py6S.

For more details on the format see FSF import guide ([pdf](http://fsf.nerc.ac.uk/resources/post-processing/library_files/Importing_Spectral_Data_Into_an_ENVI_Spectral_Library_DRAFT.pdf))

(Opening issue as a reminder I had discussed with @robintw doing this. If anyone wants the reader before a pull request is submitted to Py6S let me know).

**Comment by robintw** [comment]
Thanks @danclewley.

I've been wondering about creating a separate module (`PySpectra`?) to contain functions for reading spectra from various files. This would enable them to be used from Py6S, but also from any other modules without requiring Py6S to be installed. What do you think?

The file formats that could be included in the module, are currently:

  * USGS Spectral Library (in Py6S)
  * ASTER Spectral Library (in Py6S)
  * ENVI Plot Window ASCII export files (I have code to do this elsewhere)
  * ENVI Spectral Library (I think I have code to do this elsewhere)
  * DART Spectra files (I have code to do this elsewhere)
  * OceanOptics SpectraSuite files (I have code to do this elsewhere)
  * .sig format files (as you mention above)

Any thoughts?

**Comment by danclewley** [comment]
Having a separate module to read in spectra in different formats, so they can be passed to Py6S, is a great idea. This is actually what we were going for internally and the .sig reader is part of this. The general design is there is a single function to read spectra (which you pass in the filename and type) then there are separate classes in which readers for each format are implemented.

Instead of us making the .sig reader fit into Py6S would it be better if I create a separate repo containing our initial implementation of `PySpectra` (can't think of a better name!) and after we've figured the design out you add your importers to this?

**Comment by robintw** [comment]
Sounds perfect - thanks!

**Comment by robintw** [comment]
(Also, just while I remember to tell you, you may be interested in another module I've released: `PyMicrotops` - see https://github.com/robintw/PyMicrotops)

**Comment by danclewley** [comment]
I've set up a repository with our existing code: https://github.com/pmlrsg/PySpectra for additional importers to be added to. Any comments on design welcome (suggest opening an issue for discussion).

Marking as closed.
