### ISSUE TITLE
why Py6S cannot use in IPython?

### ISSUE THREAD

**Issue by dorbodwolf** [robintw/Py6S#34]
I can import all thing of Py6S by `from Py6S import *` in python but when I do this through IPython its throw `ImportError: No module named Py6S`. What the probably reasons ?

**Comment by samsammurphy** [comment]
This is probably a question for the [forum](https://groups.google.com/forum/#!forum/py6s), as other uses might benefit from the discussion (and you would get a quicker response for sure)

You probably have more than one version of python on your machine. Can you post the output from these commands?

```
$ which python
$ which ipython
```

**Comment by j08lue** [comment]
This is not a Py6S issue. Better close this.
