### ISSUE TITLE
how to obtain total downward or upward transmitance and path radiance?

### ISSUE THREAD

**Issue by lwk1542** [robintw/Py6S#42]
we can only obtain downward and upward transmittance of Rayleigh scattering from current function

**Comment by robintw** [comment]
Path radiance is the same as the atmospheric intrinsic radiance, and so can be retrieved as `s.outputs.atmospheric_intrinsic_radiance`.

Transmittances can be combined by multiplying them together, so to get the total downward or upward transmittance, you can multiply together the global gas transmittance and the total scattering transmittance.
