### ISSUE TITLE
model error

### ISSUE THREAD

**Issue by lizaoye** [robintw/Py6S#44]
in <module>
    early.ground_reflectance = GroundReflectance.HeterogeneousLambertian(GroundReflectance.GreenVegetation)
TypeError: HeterogeneousLambertian() missing 2 required positional arguments: 'ro_target' and 'ro_env'

**Comment by robintw** [comment]
The `HeterogeneousLambertian` function takes three arguments giving the diameter of the target, the reflectance of the target and the reflectance of the environment around the target. You've only provided one argument, which is a single reflectance.

You might be wanting to use `GroundReflectance.HomogeneousLambertian` which just takes a single argument of the ground reflectance.

**Comment by lizaoye** [comment]
> The `HeterogeneousLambertian` function takes three arguments giving the diameter of the target, the reflectance of the target and the reflectance of the environment around the target. You've only provided one argument, which is a single reflectance.
> 
> You might be wanting to use `GroundReflectance.HomogeneousLambertian` which just takes a single argument of the ground reflectance.

Thank you very much for you reply, I am know study the "case study", and the program you you provide is "early.ground_reflectance = GroundReflectance.HeterogeneousLambertian(GroundReflectance.GreenVegetation)" at line 19, can you help me ,thank you very much

**Comment by lizaoye** [comment]
I am sorry , I am a new student in this field, so please help me , when I run the case study , it has some error  I can not solve them, and I am a question about: I just copy the case study and run it ? or Do I have to change some parameters to run it ? 

thank you very much

all my best wishes

**Comment by lizaoye** [comment]
sorry to disturb you , very very sorry ,  my error because I write a error function name (I write ' HeterogeneousLambertian', but the correct function is 'HomegeneousLambertian')
