### ISSUE TITLE
AHI (Himawari-8) sensor support

### ISSUE THREAD

**Issue by jmettes** [robintw/Py6S#45]
Hi, I'd like to try and add support for Himawari-8.

I was wondering is there any intrinsic reason for the 4µm maximum wavelength? 
https://github.com/robintw/Py6S/blob/master/Py6S/Params/wavelength.py#L103

Because Himawari-8 has bands with wavelengths up to 13.3µm
https://www.data.jma.go.jp/mscweb/en/himawari89/space_segment/spsg_ahi.html#band

Himawari-8 spectral responsivity function defined here: http://www.data.jma.go.jp/mscweb/en/himawari89/space_segment/srf_201309/AHI-08_SpectralResponsivity.zip

**Comment by robintw** [comment]
Adding support for Himawari-8 would be great.

The reason for the 4um maximum wavelength is that the underlying 6S model (which Py6S is just an interface for) only supports a maximum wavelength of 4um - all of the mathematics of the model, and all of the ancilliary data that 6S uses is only defined up to 4um.

**Comment by robintw** [comment]
We have a number of sensors supported by Py6S that have bands outside of the range that 6S supports - basically, we just support the bands that are fully within the 6S wavelength range. This probably applies to a majority of the sensors that Py6S supports - so it's not a problem for Py6S itself. It obviously means Py6S can't be used for all of the bands of the sensor - but often people are just working with the optical bands so it is still very useful.

In general, models seem to support optical wavelengths or further into the infrared - but often not both, so it might be difficult to find one model that does the whole range.

**Comment by jmettes** [comment]
For my particular problem, I am more interested in the higher wavelengths. So I won't be working on adding Himawari-8 support in that case. Thanks a lot for responding so quick though!
