### ISSUE TITLE
Can the wavelength.py file be replaced by the newer  in Master?

### ISSUE THREAD

**Issue by qq2898** [robintw/Py6S#55]
I have installed Py6S in Anaconda, its wavelength.py file has only 1323 lines but the one in master is 1536 lines, can the older be replaced by the newer override directly? thank you!

**Comment by robintw** [comment]
Yes it can, alternatively you can install the master version of Py6S directly from github via pip (it will override the one you installed with Anaconda, but will use the anaconda dependencies):

`pip install git+git://github.com/robintw/Py6S.git#egg=Py6S`
