### ISSUE TITLE
use depreciated ix method which is no longer available in pandas v1.0 above

### ISSUE THREAD

**Issue by drzhouq** [robintw/Py6S#59]
https://github.com/robintw/Py6S/blob/2a606a491157d396a08bc33eaf7787b761c0828c/Py6S/SixSHelpers/aeronet.py#L115

ix has been depreciated from pandas for a while and was dropped after pandas v1.0. Suggest to replace ix with iloc. We need search entire project to refactor ix to iloc

**Comment by robintw** [comment]
Fixed in 7a6da6e.
