### ISSUE TITLE
the environment variable needs to be set on linux system

### ISSUE THREAD

**Issue by lwk1542** [robintw/Py6S#68]
After  Compiling the 6S source code, 'sixsV1.1' needs to be add in linux environment variable.
==============
open profile: sudo vi /etc/profile
add one line at the end of the file: export PATH=$PATH:/home/'xxx'/build/6SV1.1
notice: 'xxx' is your username

**Comment by robintw** [comment]
Thanks. This is actually already included in the documentation - see https://py6s.readthedocs.io/en/latest/installation.html#using-6s.
