### ISSUE TITLE
support for LWIR thermal applications

### ISSUE THREAD

**Issue by joemcglinchy** [robintw/Py6S#89]
hello, I wanted to check and see if there is any planned support for LWIR wavelengths to facilitate thermal analyses? and if not, what it may take to do so?

**Comment by robintw** [comment]
Unfortunately Py6S is just a 'frontend' for the 6S model, and the underlying 6S model doesn't support LWIR wavelengths - so it would be a huge amount of work to add support. Sorry.

**Comment by joemcglinchy** [comment]
got ya. thanks for responding!
